#!/bin/bash

GROUP="$2"
VERSION="$4"

REPORT_DIR="build/reports/pluginVerifier"
REPORT_PATH="build/reports/pluginVerifier.md"

RESULT_FILE="verification-verdict.txt"
DEPENDENCIES_FILE="dependencies.txt"

title() {
  echo -e "## ${1}\n" > ${REPORT_PATH}
}

h1() {
  echo -e "\n### ${1}\n" >> ${REPORT_PATH}
}

h2() {
  echo -e "\n#### ${1}\n" >> ${REPORT_PATH}
}

append() {
  while read -r LINE; do
    echo -e "${LINE}" >> "${REPORT_PATH}"
  done <"${1}"
}

append_as_bullets() {
  while read -r LINE; do
    echo -e "- ${LINE}" >> "${REPORT_PATH}"
  done <"${1}"
}

append_as_code() {
  echo '```' >> "${REPORT_PATH}"

  while read -r LINE; do
    echo -e "${LINE}" >> "${REPORT_PATH}"
  done <"${1}"

  echo '```' >> "${REPORT_PATH}"
}


title "Plugin Verifier Results"

for IDE_PATH in "${REPORT_DIR}"/*
do
  IDE=${IDE_PATH##*/}
  IDE_REPORT_DIR="${IDE_PATH}/plugins/${GROUP}/${VERSION}"

  h1 "${IDE}"
  append "${IDE_REPORT_DIR}/${RESULT_FILE}"

  for PATH in "${IDE_REPORT_DIR}"/*
  do
    FILE="${PATH##*/}"
    FILENAME="${FILE%.txt}"
    HEADER="${FILENAME//-/ }"

    case "${FILE}" in

      "${RESULT_FILE}")
        ;;

      "${DEPENDENCIES_FILE}")
        ;;

      *)
        h2 ":warning: ${HEADER^}"
        append_as_bullets "${PATH}"
        ;;
    esac
  done

  h2 ":arrow_double_up: Dependencies"
  append_as_code "${IDE_REPORT_DIR}/${DEPENDENCIES_FILE}"
done
