# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

complexity:
  TooManyFunctions:
    thresholdInClasses: 20
    thresholdInObjects: 20

formatting:
  AnnotationOnSeparateLine:
    active: false
  ImportOrdering:
    layout: '*'
  Indentation:
    active: true
  MultiLineIfElse:
    active: false
  SpacingBetweenDeclarationsWithAnnotations:
    active: false
